### ISSUE TITLE
missing }

### ISSUE THREAD

**Issue by jktfamily-j** [jktfamily/jktfamily.html#1]
https://github.com/jktfamily/jktfamily.html/blob/d8e24395aa67147254c2d23e88a9f4c4f0126933/blog.html#L20
https://github.com/jktfamily/jktfamily.html/blob/d8e24395aa67147254c2d23e88a9f4c4f0126933/blog.html#L21 
has a missing }

**Comment by jktfamily** [comment]
Close because  
https://github.com/jktfamily/jktfamily.html/blob/8271c3b1e3ec87b906dce13dc4ab3cc828875e97/blog.html#L22 
Is out
